baseURL: "http://example.org/"
languageCode: "en-us"
title: "Hannah Siren"
theme: "hugo-profile"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true


    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hannah Siren"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/HS.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
     textColor: "#2d150a"
     secondaryTextColor: "#51321b"
     backgroundColor: "#eeeae6"
     secondaryBackgroundColor: "#fff4f1"
     primaryColor: "#6b705c"
     secondaryColor: "#ffffff"

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Hannah Siren" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Hannah Siren."
    subtitle: "UX Designer"
    content: "Welcome to my professional portfolio"
    image: /images/hannah.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: https://www.linkedin.com/in/hannahsiren/overlay/1706200130958/single-media-viewer/?profileId=ACoAAEaSLUsBLqzuqPMVKFgP7xgN8L3nysNk64o
      download: true
      newPage: false cdf
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/hannahsiren/

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      In the spring of 2024, I will receive a BS in Information, Communication, and Technology with a minor in Innovation. I aim to leverage the skills gained from my experience in UX design, web development, sales, and project management and apply them to future experience in the technology industry. 
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "Figma"
        - "JavaScript"
        - "UI/UX Design"
        - "Google Suite"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "IT and User Experience Intern"
        company: "UTSW"
        companyUrl: "https://www.utsouthwestern.edu/"
        date: "May 2023 - August 2023"
        content: |
         - Learned to work with data efficiently, leveraging Excel's capabilities for insightful analysis. 
         - Ensured that course templates were user-friendly, visually appealing, and aligned with educational best practices.
         - Utilized Power Automate to automate repetitive tasks, improving workflow efficiency and productivity.

      - job: "Assistant Manager"
        company: "Cherry Smash"
        date: "Jan 2019 - Aug 2021"
        content: |
         - Serve and attend to approximately 300 customers per shift while providing a memorable experience.
         - Train and develop other team members while supporting general manager with operational tasks.
         - Maintained inventory and scheduled orders accordingly.
         - Organized the schedule for 10+ employees

      - job: "Small Business Owner"
        company: "Etsy"
        date: "Jan 2020 - Aug 2020"
        content: |
         - Founded and operated an online sales business specializing in handmade custom designs, overseeing all aspects of entrepreneurship including product design, marketing, and customer service.
         - Strategically marketed the product on social media platforms, effectivelly reaching a diverse customer base.
         - Managed the end-to-end process of creating, packaging, and shipping over 900 orders

      - job: "Sales Associate"
        company: "Club Pilates"
        companyUrl: "https://example.com"
        date: "March 2024 - Present"
        content: |
          - Demonstrated strong sales skills, successfully promoting membership packages and retail products to meet and exceed sales targets.
          - Contributed to marketing efforts, including social media promotion and community outreach events, to drive membership growth and brand awareness.
          - Efficiently managed front desk operations, providing exceptional customer service to members and guests
          
  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Information Technology and Communications Major"
        school: 
          name: "Florida State University"
          url: "https://www.fsu.edu/"
        date: "Expected graduation: May 2024"
        GPA: "3.624"
        content: |-
          Extracurricular Activities
            - Participated in fundraising events such as Dance Marathon and St. Jude's initiatives
            - Held leadership roles within Tri Delta, fostering teamwork and organizational skills

  # Achievements
  achievements:
    enable: true
    title: "Projects"
    items:
      - title: Mobile Applications Development
        content: Find my previous projects from my Advanced Mobile Applications Development course here!
        url: https://bitbucket.org/hes21i/lis4331/src/master/
        image: /images/s11_ProductDemo.png
      - title: Project Management of Application
        content: Collaborated in a team-based Information Technology project class to design, plan, and execute a comprehensive development project.
        url: https://docs.google.com/presentation/d/1L4Qb9kR_WhQ34VtVRIWYESlqF_ZGvPC9CBTszyJBcfI/edit?usp=sharing
        image: /images/app2.png
      - title: Redesign of Website for UX Experience
        content: Redesigned an elementery school website for an Information Architecture course at FSU.
        url: "https://docs.google.com/presentation/d/1YeJ9bx22wcL-kb14RgwRPeNaX2rJH54QAEikBUQWRY0/edit?usp=sharing"
        image: /images/elementary.png
      - title: Portfolio Website Devlopemnt
        content: Developed a portfolio website.
        url: https://github.com/hannahsiren/hugo-profile
        image: /images/portfolio.png

  # Projects
  projects:
    enable: true
    title: "Services"
    items:
      - title: Web Design
        content: Web Design experience learned from Web Application Course at Florida State University.
        image: /images/codeas.png
        badges:
          - "Java"
          - "Android Studio"

      - title: UI/UX
        content: UI/UX experience learned from User Experience Design Course and User Experience Internship at UTSW
        image: /images/application.png
        badges:
          - "Figma"
          - "Balsamiq"
          - "Adobe XD"

      - title: Social Media Management
        content: Social Media Management learned from personal experience in collaborating with brands and internship at UTSW.
        image: /images/social.png
        badges:
          - "Canva"
          - "SeedSprout"

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: Feel free to reach out if you have any projects or opportunities you'd like to discuss.
    btnName: Email me
    btnLink: mailto:hannahsiren03@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    socialNetworks:
      linkedin: https://www.linkedin.com/in/hannahsiren/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
